### ISSUE TITLE
[SPIKE] Firewall shared services

### ISSUE THREAD

**Issue by jjcollinge** [microsoft/AzureTRE#118]
### What?
We believe that it is possible to use a shared resource document type to safely make changes to "shared" Azure resources.
We will know if this is true if can successfully build a PoC on the existing solution.

### How?
Add a feedback channel via the private API.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7241190/122081677-35504000-cdf7-11eb-9e08-ba71e9383ee2.png)

Allow operations to express dependencies between each other.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7241190/122081670-341f1300-cdf7-11eb-9833-55998a7738e4.png)

Subtasks:
- [x] Write private API: #229 
- [x] Refactor RFP: #230 
- [x] Add "special" outputs to TF config: #232
- [x] Add DB trigger to update dependent resources on the back of a deployment write: #233
- [x] Refactor RCP to use private API: #234
- [x] Add shared firewall resource type
- [x] Add firewall configuration to CAF TF: #359 

## Acceptance criteria
- [ ] Build PoC of firewall shared service on existing solution.
- [ ] Document findings

Parent: #23

**Comment by marrobi** [comment]
Closing as spike complete see #23
