### ISSUE TITLE
Support automation accounts for end-to-end tests

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#1211]
Currently,  the end-to-end tests use resource owner password credentials to authenticate against the TRE API. This causes an issue in tenants with MFA enabled. As an alternative, we will create an App Registration to allow the tests to use the [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview) (preferred for this scenario).

This mirrors the work in #1232 for bundle registration.

The steps required are:

- [x] update the end-to-end tests to support using the automation account for smoke tests (added in #1296)
- [x] update the end-to-end tests to support using the automation account for extended tests (added in #1424)
- [x] document how to manually create the automation account(s) (I think this is covered by #1232)
- [x] document how to configure the automation account for end-to-end tests (#1607)

**Comment by marrobi** [comment]
Take this back, it assigns the role, but cannot get the token.

**Comment by stuartleeks** [comment]
I've got an approach to this using client credentials flow. So far this is just explorative, with manually created resources via the portal.

My planned next step is to encapsulate this in scripts etc in the repo - does that sounds like a good approach @marrobi ?

**Comment by marrobi** [comment]
I think it would be useful in a script, although given orgs are cautious around running scripts against AD, worth having the steps in the docs as a starting point to explain what is being done. That ok with yourself?

**Comment by stuartleeks** [comment]
Ok, I'll do the docs + script together. The docs make sense, and the script will help ensure that I have a clear repro of the steps required (as well as helping others working on this across environments)

**Comment by stuartleeks** [comment]
Just to capture here, the plan is to update the scripts (and docs) to use the [client credentials flow ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) for authenticating from automated flows (e.g. registering bundles in CI/CD) rather than the [resource owner password credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc) that I believe is currently used.

There is a potential future step to support managed identity, i.e. run the automation on an Azure VM with a managed identity assigned, but I'm treating that as out of scope for this piece of work.

**Comment by ross-p-smith** [comment]
Stuart - I am doing something similar for a user that needs Service Bus and Cosmos permission for local debugging - would love to see where you are on this - so I can borrow/steal

**Comment by stuartleeks** [comment]
@ross-p-smith - so far I have a manually created AAD App Registration that is configured as a TRE Admin, and a `curl` command that can be used to get a token for that App to talk to the API. I'm now working on adding that as an option to the `aad-app-reg.sh` script.

I think the steps I need for this issue are:
- [ ] Update `aad-app-reg.sh` to allow a user to be created for automation
- [ ] Update the docs with the steps needed to create this user (either via the script or manually)
- [ ] Incorporate the token retrieval for this App into the bundle registration for CI/CD
- [ ] Update E2E tests to use this App identity

**Comment by ross-p-smith** [comment]
@stuartleeks and @marrobi - I think this task is done. Liza also has this working on the new GH build

**Comment by stuartleeks** [comment]
I think we still need the documentation for manually creating the AAD accounts?

**Comment by stuartleeks** [comment]
I think this task is done now (just merged in #1607).

@marrobi ?

**Comment by marrobi** [comment]
@stuartleeks @ross-p-smith good work, yes, happy to be closed if you are.
