### ISSUE TITLE
Resource processor reports bundle execution events to state store

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#135]
## Description

Resource processor needs to emit and report on bundle execution progress and report back to state store. Eventually this information will be retrieved by a caller through the management API.

## Acceptance criteria

- [x] Bundle execution events captured by resource processor
- [x] Bundle execution events persisted in state store
- [x] Resource updated with relevant deployment status, e.g., *deploying*, *succeeded*, *failed*, etc.

## Tasks
- [x] Read ACI Log #256 
- [x] Write to SB #257 
- [x] Read SB from background task #254
- [x] Write to Cosmos from background task #255
- [x] Verify return channel end to end #300

**Comment by christoferlof** [comment]
Need design and decision on how processor gets the events persisted in state store.
