### ISSUE TITLE
Workspace Bundle registration

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#138]
## Description

As a TRE service integrator
I want to publish my newly created workspace bundle to the bundle registry and have the resource spec created for it 
So that API clients can see the resource spec and instantiate workspaces based of it

## Acceptance criteria

- [x] Workspace Bundles can be registered by a TRE service integrator
- [x] Registered bundles show up as `workspace-templates` through API.
- [x] The newly created workspace template can be referenced and successfully used in a new workspace request (`POST /workspaces`)

## Related tasks

- [x] Implement publish_workspace.sh script #219
- [x] Implement POST /workspace-templates - takes full resource spec with parameters etc. returns the created resource spec as stored in the DB #180 
- [x] Implement GET /workspace-templates- returns a list of all the resource spec names #181
- [x] Implement GET /workspace-templates/{template_name} - returns the current workspace template for that template name #182

**Comment by christoferlof** [comment]
One way of implementing this could be to listen for ACI events via Event Grid, have a function do the `explain` on the newly added bundle and add the parameters to the state store.
