### ISSUE TITLE
Create baseline resource templates

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#14]
This task is to setup the initial resource templates from which we will continue to build.  Let's ensure we have the below baseline templates and can deploy them into our shared dev environment.

- [x] Shared services template #28 
- [x] Workspace template #29
- [x] Workspace service template #30
- [x] Provision resources with above templates in shared dev environment.
   - [x] Provision two workspaces individually after the shared services have been provisioned.  
- [x] Structure the repository and templates etc in accordance to any requirements from #13 

If not explicitly mentioned, all services exposed only through private endpoints to restrict access from the Internet.

## Core (Shared) services
- VNet 
- KeyVault
- App Service plan 
   - KeyVault integration using Managed Identity

## Workspace
- VNet
   - Peered with Core (Shared) services VNet 
- KeyVault
- App Service plan
   - KeyVault integration using Managed Identity 

## Workspace service
- Storage account

**Comment by christoferlof** [comment]
@marrobi can you please push your baseline templates as draft PRs for #28, #29, #30? Thanks!
