### ISSUE TITLE
Update existing TRE and Azure resources

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#141]
As an Azure Administrator 
I would like to be able to update the deployed infrastructure and code within an Azure TRE instance, either manually or using CI/CD.
So that I can keep the TRE infrastructure and code up to date.
 
As a TRE adminstrator
I want to update workspaces
So that I can rename them

As a workspace owner
I want to update workspace services
So that I can make changes such as increase the amount of compute or change security settings

As a researcher
I want to update user resources
So that I can resize VMs

## Acceptance Criteria
- [x] Explore and prepare proposal for updates that can be done on a TRE instance.
- [x] #1744
- [x] Each template schema needs define which properties can (or cannot) be updated. These are returned as readonly properties by the API on get template (for an update operation) and validated by the API on PUT/PATCH that they haven't changed.
- [x] On workspace update the bundles updates with new parameters via an update message - this mechanism could also be used to retry a failed bundle deployment.

## Tasks
- [x] #1240

**Comment by marrobi** [comment]
@damoodamoo Most of this is done I believe? Can we update the template version of a resource and hence bundle?

**Comment by damoodamoo** [comment]
Yes 3/4 of the tasks above are done as part of #1240 . You currently cannot update the template of a resource - you can update the properties and the `isEnabled` flag.

**Comment by tamirkamara** [comment]
@marrobi I think we can close this as complete. do you agree?

**Comment by marrobi** [comment]
Happy to close it, we need to make sure we reinstate the workspace upgrade flow.
