### ISSUE TITLE
Ability to be able to debug E2E tests

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1420]
As a TRE Developer I want the variables defined in various .ENV files to be the same across the Unit Tests / E2E Tests / the api_app and the resource Provider so that I can have a central .ENV file that is generated for me.

## Acceptance criteria

- [x] USERNAME= TEST_USER_NAME #1499
- [x] PASSWORD=TEST_USER_PASSWORD #1499
- [x] CLIENT_ID=TEST_APP_ID #1499
- [X] ~~TEST_WORKSPACE_APP_ID=??~~
- [X] RESOURCE=API_CLIENT_ID #1424 
- [X] SCOPE="api://${RESOURCE}/user_impersonation" #1424
- [X] WORKSPACE_SCOPE="api://${TEST_WORKSPACE_APP_ID}/user_impersonation" #1424
- [X] Amend the aad reg script to tell users to copy the values into /workspaces/AzureTRE/templates/core/.env #1437 
- [x] Amend the workspace registration script so that the automation Admin App is given the workspace Owner permission #1468
