### ISSUE TITLE
Refine API contract based on recent demo comments

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#161]
## Description

As we now have the first version of the API with request and response formats for the /workspaces resource, we've identified a few areas of improvements for increased usability. 

## Acceptance criteria

- [x] Environment variables added for the API #164 
- [x] API follows spec per comment #165
- [x] Workspace ID (4 digit) is calculated #166
- [x] Resource spec uses latest version #167

## Topics to decide on

- [x] Desired request and response formats for `/workspaces` resource. 
   -  Version, friendly name, resourceSpec vs workspaceSpec etc.
- [x] Should we query by sequential (human friendly) workspace id/name or system generated resource?
- [x] Bundle parameters that are not required/expected to be provided by end-user should not be part of request?
   -  `workspace_id` should be generated and not provided by the user
   -  `core_id` is static per TRE instance

**Comment by TessFerrandez** [comment]
the workspace resource should look as follows:

    {
	"id": GUID #generated by the API
	"friendlyName": "Tess workspace",	# shown in the UI
	"workspaceURL": ""	# default entry point to the workspace for the researcher (not filled in for right now)
	"status": "not_deployed" # status of the workspace deployment
	"description": "blabla" #provided by the user at request time
	"resourceSpec": {
             "name" : "bundlename", # provided by the user
             "version": "0.1.0", # latest version CALCULATED BY API
             "parameters" : {
                      "location" : "westeurope"   # for now default TRE location (provided with ENV VAR)
                      "workspace_id" : "0001"     # 4 char string - continuous number - calculated by API
                      "core_id": "mytre-dev-3142" # ENV VAR (same for all workspaces in TRE instance)
                      "address_space": "10.2.1.0/24" # hard-coded for now - calculated by API in later issue
             }
        }
        "isDeleted": false # whether the request is deleted and should be cleaned up (ex. if service bus fails) 
        "resourceType": "workspace"
    },

- GET /workspaces - returns a list of all the resources as is (if not isDeleted)
- GET /workspace/{workspace_id} - returns a single workspace resource (if not isDeleted) - workspace_id here is the GUID
- POST /workspace
    - INPUT: friendlyName, workspaceType (resourceSpec/name), description
    - OUTPUT: 202 - id (GUID)
