### ISSUE TITLE
Composition service with initial management API

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#17]
To be detailed, based on outcomes from the design task #13 

- [x] Complete exploration of possible options and provide recommendation on approach #13 
- [x] Add additional detail to this issue based on outcomes of above

**API**

- [x] Implement `POST /workspaces` #112 
- [x] Implement `GET /workspaces` #113  
- [x] Register workspace template  #180 , #181 , #182  
- [x] Validate API requests against workspaceTemplate parameters #142
- [x] Trigger workspace bundle #96 

**API Auth**
- [x] Register API with Azure AD #95
- [x] Register workspace with Azure AD, #211 
- [x] Enforce auth on `/workspaces` endpoint #96 
- [x] Enforce auth on `/workspaces{workspace_id}` endpoint #221 
- [x] Retrieve 'my' workspaces #208 
- [x] Docs #236 

**Bundles & Deployment execution**
- [x] Composition service logs and events forwarded to App Insights #174 
- [x] Add bundle registry to TRE templates #65 
- [x] Workspace bundle registration #138 
- [x] Create sample workspace bundle #43 
- [x] Invoke and install workspace bundle #64 
- [x] Resource processor reports bundle execution events to state store #135 
- [x] Document workspace authoring experience #59

**Comment by christoferlof** [comment]
Exploration completed, description of approach pending.
