### ISSUE TITLE
[epic] AuthN + AuthZ

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1802]
- [x] Implement base MSAL for root level and get access token for workspace activities
- [x] Handle `interaction_required` exceptions when token has timed out
- [x] Implement RBAC to enable showing / hiding UI elements based on root / workspace role
- [x] Handle the user landing on a workspace page after a token timeout 
- [x] Test behaviour when user not in expected role
- [x] Error messages + screens
- [x] User dropdown with Logout
- [x] "you have logged out" page
