### ISSUE TITLE
[epic] Workspaces

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1803]
- [x] `WorkspaceCard` component to accept a workspace as a prop and render the details according to the UI design here https://xd.adobe.com/view/b31fd46c-82c6-4171-885e-5a5e429f3c81-e64c/screen/b37d0ba7-56c7-4731-b3bb-2ae9e206cd3f. Initial implementation (Title, description, and (i) icon with overlay panel) only. Clicking the title should take the user into the `/workspaces/{workspaceId}` page.
- [x] `WorkspaceActions` component - a popout menu accessible via a `...` icon. To be used in the workspace card, viewable on by TREAdmin users. Mock here: https://xd.adobe.com/view/b31fd46c-82c6-4171-885e-5a5e429f3c81-e64c/screen/b37d0ba7-56c7-4731-b3bb-2ae9e206cd3f
- [x]  Workspace home page - awaiting UI mocks - will contain a few components, but can show basic summary for now.
- [x] #1862
