### ISSUE TITLE
[epic] TRE-UI CI/CD

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1806]
- [x] Include in the root makefile
- [x] Use a feature flag in a `.env` to enable the user to set `DEPLOY_UI` to `true` or `false` 
- [x] Deploy the UI to Static Web Apps
- [x] Set config from main build
- [ ] ~~(Optional) - Include the UI build in PR builds, to enable reviewers to navigate it and review it inplace.~~
