### ISSUE TITLE
[epic] Notifications Panel

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1807]
Implement a notifications panel, using the Azure Portal notifications panel as a guide. 

For this implementation - it will:
- Only track operations passed to it from other components
- NOT try to gather all running operations on startup
- Only track operations the current user has triggered

To do:
- [x] Design + spike how this will interact with other components, likely via the Context API
- [x] 'bell' icon in the top nav bar opens a slideout panel
- [x] A card is rendered for each long running operation
- [x] When an operation completes, a toast notification is fired
- [x] Consolidate all the polling logic into this set of components
- [x] When an operation is triggered elsewhere in the app, the Operation URL to poll will be passed to the notifications panel
- [x] Get the polling frequency from config

Future: (moved to separate task)
