### ISSUE TITLE
[epic] Shared Services

### ISSUE THREAD

**Issue by damoodamoo** [microsoft/AzureTRE#1808]
- [x] Shared services page accessible from the app root (possibly under 'Admin' link)
- [x] List all Shared Services in cards, the same as Workspaces are listed
- [x] Clicking into each card navigates to `/shared-services/{sharedServiceId}` page
- [x] Options to create new shared service, update existing etc.
- [x] Should reuse the `CreateResource` component
