### ISSUE TITLE
Azure Machine Learning for InnerEye workspace service

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#19]
## High-level requirements
- Deployed to VNet and adheres to the TRE workspace egress rules.
- Only accessible from the Virtual Desktop service in the same workspace.
   - Azure AD authentication 
- Ability to manage AML clusters and compute instances within the TRE workspace and not outside of the TRE workspace.
- AML storage provisioned in the TRE workspace.
- No public endpoints.
- Pass specified level of IG (Information Governance) - see #16 
   - Capture potential show-stoppers. 
- Configuration on which services within AML should be enabled and accessible. e.g. Interactive Notebooks on/off. 
- Model export between AML instances , potentially in different TRE workspaces (This will be handled as part of the data sharing feature #33).
- Ability to deploy models.
- Ability to connect to AML compute from Virtual Machines within the same TRE workspace.

## Spikes
- [x] Explore AML configuration options and requirements for closed VNet setup #25 

## Implementation
- [x] Refactor templates from spike #25
- [x] Create workspace service bundle #132 
- [x] App Package shared service #21 
- [x] Source code mirror shared service #22 
- [x] #584

**Comment by iankelly-github** [comment]
- There is no mention of AML Compute Instances, can users of this workspace manage these also? I think they should be able to.
- AML work spaces can use privately provisioned clusters, we should clarify if this is a supported scenario for us?

**Comment by ant0nsc** [comment]
Should we think of a way of accessing private python packages? It's a setup we had to use with one customer. Code is stored in the organization's AzureDevOps instance, and gets built into a private Python package. This package is later accessed when building the docker image for runs in AML.

**Comment by christoferlof** [comment]
> * There is no mention of AML Compute Instances, can users of this workspace manage these also? I think they should be able to.
> * AML work spaces can use privately provisioned clusters, we should clarify if this is a supported scenario for us?

Agree, @iankelly-github . We want to support as many features of AML as possible.

**Comment by christoferlof** [comment]
> Should we think of a way of accessing private python packages? It's a setup we had to use with one customer. Code is stored in the organization's AzureDevOps instance, and gets built into a private Python package. This package is later accessed when building the docker image for runs in AML.
> Or is that within the realms of #21 ?

Yes @ant0nsc. We plan to support that scenario with the *Package Mirror* shared service.

**Comment by christoferlof** [comment]
ℹ Please note: "Workspace" is an overloaded term , especially in the context of AML which also has a definition of a workspace.  An AML Workspace is part of the AML service which can be provisioned within a TRE workspace.
