### ISSUE TITLE
Airlock processor handles request cancellation

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1968]
## Description

As an Airlock processor in TRE
I want to be able to be able to consume and operate on cancel event
So that requests cancelation are handled

## Acceptance criteria

- [ ] Data artifact are copied to the 'canceled' containers (import cancel or export cancel)
- [ ] Step result event is sent by the airlock processor when the data copy is done
- [ ] Data deletion event should be sent (which is handled by #1963 )
- [ ] Data Steward can no longer access previously used storage (call method by #1965 )
- [ ] A notification event with all the details sent to Event grid (to be consumed by #1964 )

**Comment by eladiw** [comment]
@joalmeid @marrobi  @yuvalyaron 
The story talks about moving the data to a NEW storage accound called cancelled.
I think its an overkill, how about we simply delete the data of a cancelled request.

Reminder, we allow to cancel only in-review requests or draft requests, so its not possible to cancel a rejected or approved requests for example...

**Comment by marrobi** [comment]
I think so... we don't really want the data hanging around.

**Comment by eladiw** [comment]
@tamirkamara @yuvalyaron so let's delete the data
