### ISSUE TITLE
March 2021.1 Plan

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#20]
For this milestone we should focus on getting ready to implement the first workspace services. Create the baseline templates and explore how we should implement the deployment service and its siblings.

 - [x] Establish repo with contributions and support guidelines. #2, #4
 - [x] Start documentation with initial section on concepts. #3 
 - [ ] Design management API contract. #12 
 - [x] Explore deployment service and management API and configuration store options, #13 
 - [x] Explore Azure Machine Learning configuration options for closed VNet setup #19, #25
 - [x] Explore Virtual Desktop service options #18, #26  
 - [ ] Build baseline resource templates. #14 
 - [ ] Design authentication and authorization. #15

**Comment by christoferlof** [comment]
Closing
