### ISSUE TITLE
Implement AUTH for the management API - Master Story

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#305]
## Description

As an Azure TRE administrator
I want to make sure that access is appropriately restricted to the management API
So that we don't have data leakage or unwanted templates/workspaces created

## Acceptance critiera

- [x] Authentication/authorization is implemented with oauth2 and in such a way that AAD is replaceable (by writing a new auth component) to other auth providers in the future
- [x] Auth is done in this iteration with AAD - and through AAD Apps that have assigned users/roles
- [x] API access is restricted per the table below
- [x] Auth model is documented

| Endpoint | Access | Comment |
| -- | -- | -- |
| GET /workspaces | Researcher/owner - assigned to the workspace - only the workspaces you belong to are returned. | TRE Admin can see all |
| GET /workspaces/{workspace_id} | Researcher/owner - assigned to the workspace |  TRE Admin can see all |
| POST /workspaces | TRE Admin | To create a workspace - the admin has to manually create an AAD app and provide it when creating the workspace |
| GET /workspacesTemplates | TRE Admin | |
| GET /worskpacesTemplates/{name} | TRE Admin | |
| POST /workspacesTemplates | TRE Admin | |

## Tasks - and sub stories

- [x]  **[M]** #95 
- [x] **[M]** #211 
- [x] **[M]** #306 
- [x]  **[M]** #310
- [x]  **[M]** #307
- [x]  **[M]** #208
- [x]  **[S]** #221
- [x]  **[M]** #96 
- [x]  **[S]** #311
- [x]  **[S]** #313
- [x]  **[S]** #312
- [x] **[S]** #236
- [x]  **[S]** #314 
- [x]  #340
