### ISSUE TITLE
Implement AUTH component for AAD

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#307]
## Description

As a TRE Admin
I want to ensure that only the researchers/owners that have access to a workspace can see the workspace info
So that information is not leaked

This story creates an auth component for AAD that can be used by authentication/authorization

## Acceptance critiera

- [ ] The component can be dependecy injected into auth

## Tasks

- [ ] Given a user - retrieve the workspaces a user has access to #308
- [ ] Given a user and a workspace - retrieve the users permissions on this workspace #309
