### ISSUE TITLE
[Story] Provide JSON schema for API validation and UI generation

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#420]
## Description

As a TRE Developer
I want to receive an JSON Schema that represents the input parameters for the resource being deployed
So that I can create a UI using a library such as https://jsonforms.io/

As an API
I want to use a JSON Schema for a resource template
So that I can validate input parameters using a library such as https://python-jsonschema.readthedocs.io/en/stable/

As a TRE service integrator
I want to provide a JSON Schema document with my templates
So that I get appropriate values for resource deployment

## Acceptance criteria

- [x] #509
- [x] #526
- [x] #508

## Tasks
- [x] Create workspace and vanilla bundle json schema files
- [x] Enable storage of template json schema when template registered 
- [x] On get workspace template merge the workspace schema (see below) and bundle schema and return to user
- [x] On create workspace carry out validation against the merged json schema and store parameters
- [x] Ensure workspace deploys (only selected parameters will be required)

**Comment by marrobi** [comment]
Each resource type has a standard set of parameters provided by the system and a standard set provided by the user, and then custom parameters:

Workspaces have the following system parameters, each bundle must use as part of deployment:

```json
{
            "azure_location": "",
            "workspace_id": "",
            "tre_id": ""
}
```
The following user provided parameters are not used for bundle deployment, but are required for all workspaces:

```json
{
            "display_name": "",
            "description":""
}
```

Workspace authors can also request additional parameters for use by the bundle:

```json
{
            "address_space": "",
            "no_of_vms":""
}
```

Then there are also auth parameters that need to be provided by the user dependent on the the configured auth provider:
```json
{
    "appRegId": ""
}

**Comment by marrobi** [comment]
The GET /workspace-template/{template_name} API should return these as a **single** schema that can be used create a UI using a library such as https://jsonforms.io/.

The returned values by POST /workspaces, should be validated against the schema and stored as resource parameters in the state store.
