### ISSUE TITLE
[Story] Create resource processor supporting managed identity and vnets

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#445]
## Description

As a Cloud Administrator
I want an resource processor that uses managed identities, can be deployed on a VNET and supports docker in docker
So that I do not have to provide a service principal for deployments, can carry out data plane operations, and can deploy nested porter bundles

## Acceptance criteria

- [x] Resource processor deployed on a vnet with access to workspace data plane
- [x] Resource processor uses managed identities to deploy bundles
- [x] azureml-devtestlabs workspace successfully deploys via API
- [x] #492

## Tasks
- [x] #452
- [x] #480
- [x] #456
- [x] #457
- [x] #496
- [x] #506
- [x] #533
