### ISSUE TITLE
[Story] Add API functionality to delete workspace

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#458]
## Description

As a TRE Administrator
I want to be able to delete a workspace
So that the resources are no longer deployed to Azure

## Acceptance criteria

- [ ] Administrator can delete workspace that has already been disabled -- DELETE /api/workspaces/{workspace_id}
- [ ] If attempting to delete an enabled workspace - this should return an error "workspace must be disabled before being deleted"
- [ ] If attempting to delete a workspace with "non-deleted" workspace-services - this should return an error stating that you need to delete the workspace-services first

When deleting a workspace:
- [ ] Cloud resources are removed
- [ ] Status changes to deleted
- [x] Workspace is not available through -- GET /api/workspaces/ or GET /api/workspaces/{workspace_id}

## Tasks

-  [x] #565
