### ISSUE TITLE
Configure Gitea for Source Code Mirroring

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#544]
Story is part of feature #22

## Description

As a TRE Researcher
I want source code mirroring with Gitea enabled in my workspaces
So that I can make use of code written outside the workspace boundaries

## Acceptance critiera

- [x] TRE researcher can mirror source code in existing git repositories using Gitea
- [x] Solution is documented so that new TRE researchers can understand how to use it

## Tasks

- [x] Gitea Infrastructure set up #214 
- [x] Gitea registration configured #348
- [x] Secure admin login credentials #542
- [x] Gitea configured to connect to mySQL via SSL #347
- [x] Solution documented #436 
- [x] Mount Gitea to a storage account #567 
- [x] Upgrade terraform provider version #571 
- [x] #653

**Comment by christoferlof** [comment]
Configuring backup extracted to stand-alone issue to not block 0.2
