### ISSUE TITLE
[Story] Implement GET /api/workspace-service-templates/{service_template_name}/user-resource-templates

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#558]
## Description

As a TRE User
I want to list all user-resource-templates available to add to a given workspace-service
So that I can create user-resources

## Acceptance critiera

- [x] GET /api/workspace-service-templates/{template_name}/user-resource-templates Returns name, description
- [x] GET /api/workspace-service-templates/{template_name}/user-resource-templates/{template_name} returns enriched template
- [x] all endpoints available to TRE users

## Tasks

- [x] #611
- [x] #639 
- [x] #612

**Comment by TessFerrandez** [comment]
@marrobi please check if this looks ok - added to backlog per yesterdays discussion

**Comment by marrobi** [comment]
@TessFerrandez  Do you mean list user-resource-templates?
