### ISSUE TITLE
[Story] Add E2E tests for missing APIs

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#595]
## Description

As a TRE Developer
I want to be aware when we introduce regressions in the code
So that I can investigate them promptly when they happen

## Acceptance critiera

- [x] Tests for disable/enable workspaces #622 
- [x] Tests for delete workspaces #622
- [x] Tests for get workspace_service_temlates #642

All of these may or may not need to be tested and new APIs are continuously getting added - we should probably split this story by API area
