### ISSUE TITLE
STORY: Create workspaces API resource collection

### ISSUE THREAD

**Issue by christoferlof** [microsoft/AzureTRE#62]
Workspaces are created, updated, retrieved and deleted through the `/workspaces`  resource collection on the API.

- Expose resource collection from HTTP API.
- CRUD operations for workspaces based on defined data model 
- Resource state stored in state store
- Initialize required Cosmos containers and data.

## Acceptance critiera

- [x] Bootstrap cosmos db with /workspaces container #111 
- [x] Workspaces resource collection exposed in api
- [x] Workspaces persisted, and retrieved from State store
   - [x] `[GET] /workspaces` - returns all resource documents that are not marked as deleted #114
   - [x] `[POST] /workspaces` - creates a resource document in the state store #112 
   - [x] `[GET] /workspaces/{workspace_id}` - returns the given resource document from the state store #113

**Comment by christoferlof** [comment]
Please focus on POST /workspaces to support the end-to-end create scenario.

**Comment by TessFerrandez** [comment]
@christoferlof and @Lybecker - can you clarify Workspaces resource collection exposed in api - IMHO the next few criteria satisfies that implicitly but just want to verify so I am not making assumptions about what it means

**Comment by TessFerrandez** [comment]
@christoferlof and @Lybecker - we currently don't have a physical data model, do we need to create one, or can we use a minimal assumed set for this story, and then incrementally add as we need?

**Comment by TessFerrandez** [comment]
@christoferlof @Lybecker - I updated the acceptance criteria 

`[GET] /worksapces` - returns all resource documents **that are not marked as deleted** - can you verify if my understanding here is correct, or should it return all?

**Comment by christoferlof** [comment]
> @christoferlof and @Lybecker - can you clarify Workspaces resource collection exposed in api - IMHO the next few criteria satisfies that implicitly but just want to verify so I am not making assumptions about what it means

@TessFerrandez - Correct, *exposing the workspaces resource collection* is getting the `/workspaces` route in place with the basic resource state operations of post, put, get, delete.

**Comment by christoferlof** [comment]
> @christoferlof and @Lybecker - we currently don't have a physical data model, do we need to create one, or can we use a minimal assumed set for this story, and then incrementally add as we need?

@TessFerrandez  minimal assumed set for this story please, and then we add as we need. Should be aligned with the logical data model though.

**Comment by christoferlof** [comment]
> @christoferlof @Lybecker - I updated the acceptance criteria
> 
> `[GET] /worksapces` - returns all resource documents **that are not marked as deleted** - can you verify if my understanding here is correct, or should it return all?

@TessFerrandez correct, only return workspaces that are not marked as deleted.
