### ISSUE TITLE
[Task] E2E Smoke test should delete Workspace through API

### ISSUE THREAD

**Issue by Lybecker** [microsoft/AzureTRE#622]
## Description

As a developer
I want to the smoke test to use the TRE API to delete Workspace after completion
So that we exercise the TRE API and the status of the state store (cosmos) is correct

## Tasks
- [ ] Add a test to delete a disabled workspace, verify that workspace is deleted
- [ ] Add a test to disable/enable workspace

## Acceptance criteria

- [ ] On successful execution of smoke test, the Azure resources are cleaned up via the TRE API
- [ ] On unsuccessful execution of smoke test, the Azure resources should be cleaned up
