### ISSUE TITLE
Validate the new workspace-service/user-resource scenarios

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#623]
## Description

As a TRE developer
I want to ensure that the new features added to create workspace-services and user-resources work all the way as expected
So that we can release the feature

## Background

We have added a number of new concepts (user-resources, workspace-services etc.) and APIs - but we have not taken them all the way through the system. There are lots of little caveats here that may cause them to not work as expected, but since they are merged to develop, we need to ensure they work.

Some examples: workspace-services can by definition be added to any workspace - but have we thought this through all the way? how is the workspace connected to the right subnet (what if the workspace has multiple etc.)

## Acceptance criteria

- [x] E2E validation of the workspace-service APIs - e.g. deploying a workspace-service, validating that it does successfully deploy and get updated
- [x] User documentation on how the features should work
- [x] For each layer, think through all the assumptions made for successful deployment, listing various potential scenarios that we think may (or may not) be implemented completely and validate these scenarios - creating bugs/stories for where it fails
- [x] Document workspace service compatibility, i.e., which workspace services are compatible with which workspace template.
- [x] For each layer, create bugs for any inconsistencies between current behavior and expected behavior

## Tasks

- [x] #643
- [x] #832

**Comment by TessFerrandez** [comment]
@Lybecker this is a start of the story to do a more thorough validation of the new functionality that was added to solidify it.

**Comment by christoferlof** [comment]
It would be a good idea to write end-to-end tests for the VM service imo, perhaps we can be more explicit about which tests to write in this story.

**Comment by christoferlof** [comment]
Since it's only the end-to-end tests for user resources missing from this - I'll close this one and create a new story for the missing end-to-end tests to not block. User resource tests might be pushed to future milestone.

**Comment by christoferlof** [comment]
Pushing #831 to it's own task to not block this one.
Closing.
