### ISSUE TITLE
[Story] Validate API Access

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#667]
## Description

As a TRE Admin
I want to make sure that all API endpoints give access only to the users that should have access
So that we don't have unauthorized access

## Acceptance criteria

- [x] For all API endpoints - manual verification that they are restricted as defined (check with Marcus if unsure)
- [ ] Documentation on who has access to what as part of the API docs ( Also verify  [user role document](https://github.com/microsoft/AzureTRE/blob/develop/docs/user-roles.md) so it's aligned)
- [x] Unit Tests verifying that access is correctly set for all endpoints

## Tasks

- [x] #765 
- [x] #766
- [x] #767
- [ ] #768

**Comment by tamirkamara** [comment]
An example we saw: a user that has workspace level membership but didn't have any TRE API memberships was able to create a new user-resource.
