### ISSUE TITLE
Change API URIs to long form

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/AzureTRE#762]
## Description

As a user of the API
I want to see the hierarchy in the API URIs
So that I can see how the resources fit

## Acceptance criteria

- [x] Change GET /api/workspace-services/{services_id} to /api/workspaces/{workspace_id}/workspace-services/{services_id}
- [x] Change GET /api/workspace-services/{service_id}/user-resources to /api/workspaces/{workspace_id}/workspace-services/{service_id}/user-resources
- [x] Change GET /api/user-resources/{resource_id} to /api/workspaces/{workspace_id}/workspace-services/{service_id}/user-resources/{resource_id}
- [x] Validate the chain in all cases - i.e. validate that the resource_id actuall belongs to service_id and that service_id actually belongs to workspace_id -- else 404

## Tasks

- [x] #796
- [x] #797

**Comment by TessFerrandez** [comment]
Suggested sprint candidate for next sprint @marrobi @christoferlof

**Comment by christoferlof** [comment]
We can shorten the long form if we go with the initial design as proposed in #12 
`GET /workspaces/{workspace_id}/services/{workspace_service_id}/resources/{resource_id}`, for instance

**Comment by TessFerrandez** [comment]
Looks nice and clean @christoferlof - let's check with @marrobi when he gets back -- I can do the longer version now, the switch to the shorter (services vs. workspace-services etc.) can be done in a separate PR pretty easily
